local cfg = {}

cfg.armas = {
	["tazer"] = { index = "tazer", nome = "WEAPON_STUNGUN", ammo = 0},
	["cassetete"] = { index = "cassetete", nome = "WEAPON_NIGHTSTICK", ammo = 0},
	["lanterna"] = { index = "lanterna", nome = "WEAPON_FLASHLIGHT", ammo = 0},
	["extintor"] = { index = "extintor", nome = "WEAPON_FIREEXTINGUISHER", ammo = 0},
	["glock"] = { index = "glock", nome = "WEAPON_COMBATPISTOL", ammo = 5000},
	["mp5"] = { index = "mp5", nome = "WEAPON_SMG", ammo = 5000},
	["sigsauer"] = { index = "sigsauer", nome = "WEAPON_COMBATPDW", ammo = 5000},
	["remington"] = { index = "remington", nome = "WEAPON_PUMPSHOTGUN_MK2", ammo = 5000},
	["m4a1"] = { index = "m4a1", nome = "WEAPON_CARBINERIFLE", ammo = 5000},
	["faca"] = { index = "faca", nome = "WEAPON_KNIFE", ammo = 0},
	["canivete"] = { index = "canivete", nome = "WEAPON_SWITCHBLADE", ammo = 0},
	["m1911"] = { index = "m1911", nome = "WEAPON_PISTOL", ammo = 5000},
	["m1922"] = { index = "m1922", nome = "WEAPON_VINTAGEPISTOL", ammo = 5000},
	["hk"] = { index = "hk", nome = "WEAPON_SNSPISTOL", ammo = 5000},
	["mtar"] = { index = "mtar", nome = "WEAPON_ASSAULTSMG", ammo = 5000},
	["thompson"] = { index = "thompson", nome = "WEAPON_GUSENBERG", ammo = 5000},
	["ak"] = { index = "ak", nome = "WEAPON_ASSAULTRIFLE", ammo = 5000},
	["ak2"] = { index = "ak2", nome = "WEAPON_ASSAULTRIFLE_MK2", ammo = 5000},
	["five7"] = { index = "five7", nome = "WEAPON_PISTOL_MK2", ammo = 5000},
	["deuxtroll"] = { index = "deuxtroll", nome = "WEAPON_RAYPISTOL", ammo = 5000},
	["patriot"] = { index = "patriot", nome = "WEAPON_CARBINERIFLE_MK2", ammo = 5000},
	["uzi"] = { index = "uzi", nome = "WEAPON_MICROSMG", ammo = 5000},
	["appistol"] = { index = "appistol", nome = "WEAPON_APPISTOL", ammo = 5000},
	["desert"] = { index = "desert", nome = "WEAPON_PISTOL50", ammo = 5000},
	["hk2"] = { index = "hk2", nome = "WEAPON_SNSPISTOL_MK2", ammo = 5000},
	["flare"] = { index = "flare", nome = "WEAPON_FLAREGUN", ammo = 5000},
	["revolver"] = { index = "revolver", nome = "WEAPON_REVOLVER", ammo = 5000},
	["revolver2"] = { index = "revolver2", nome = "WEAPON_REVOLVER_MK2", ammo = 5000},
	["rd2"] = { index = "rd2", nome = "WEAPON_DOUBLEACTION", ammo = 5000},
	["trabuco"] = { index = "trabuco", nome = "WEAPON_MARKSMANPISTOL", ammo = 5000},
	["minimp5"] = { index = "minimp5", nome = "WEAPON_SMG_MK2", ammo = 5000},
	["tec9"] = { index = "tec9", nome = "WEAPON_MACHINEPISTOL", ammo = 5000},
	["g36"] = { index = "g36", nome = "WEAPON_SPECIALCARBINE", ammo = 5000},
	["g362"] = { index = "g362", nome = "WEAPON_SPECIALCARBINE_MK2", ammo = 5000},
	["rpg"] = { index = "rpg", nome = "WEAPON_RPG", ammo = 5000},
	["minigun"] = { index = "minigun", nome = "WEAPON_MINIGUN", ammo = 5000},
	["fogos"] = { index = "fogos", nome = "WEAPON_FIREWORK", ammo = 5000},
    ["paraquedas"] = { index = "paraquedas", nome = "GADGET_PARACHUTE", ammo = 0},
    ["soco"] = { index = "soco", nome = "WEAPON_KNUCKLE", ammo = 0},
    ["sinuca"] = { index = "sinuca", nome = "WEAPON_POOLCUE", ammo = 0},
    ["machado"] = { index = "machado", nome = "WEAPON_HATCHET", ammo = 0},
    ["golf"] = { index = "golf", nome = "WEAPON_GOLFCLUB", ammo = 0},
    ["all"] = {"five7", "glock", "hk", "ak", "ak2", "g36", "g362", "mp5", "sigsauer", "remington", "m4a1", "patriot", "canivete", "faca", "mtar", "thompson", "paraquedas"}
}

return cfg